### ISSUE TITLE
config with new uart section not working

### ISSUE THREAD

**Issue by ricerweb** [elupus/esphome-nibe#11]
Hi, i had a working setup (esp32+max485) with the "old" config: 

```
nibegw:
  dir_pin: GPIO4
  rx_pin: GPIO3
  tx_pin: GPIO1
  uart_id: 1
  udp:
    target:
      - ip: 10.0.0.163
        port: 10090
    source:
      - 10.0.0.163
  acknowledge:
    - MODBUS40
  constants:
    - address: MODBUS40
      token: ACCESSORY
      data: [
            0x0A, # MODBUS version low
            0x00, # MODBUS version high
            0x01, # MODBUS address?
      ]
```

I tried to update it with the new uart section, but my heat pump is going constantly into an error. 

```
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
nibegw:
  udp:
    target:
      - ip: 10.0.0.163
        port: 10090
    source:
      - 10.0.0.163
  acknowledge:
    - MODBUS40
  constants:
    - address: MODBUS40
      token: ACCESSORY
      data: [
            0x0A, # MODBUS version low
            0x00, # MODBUS version high
            0x01, # MODBUS address?
      ]
```
